SHOW_FACE_RECTANGLE_2D = True
SHOW_FACE_RECTANGLE_3D = True

SHOW_NOSE_RAY = False
SHOW_LEFT_GAZE_RAY = False
SHOW_RIGHT_GAZE_RAY = False

SHOW_PUPIL_POINTERS = True

SHOW_LEFT_RAY = False
SHOW_RIGHT_RAY = False
SHOW_MEAN_RAY = True

ENABLE_SMOOTH_BBOX_RENDER = True

FIX_BARREL_DISTORTION = False
